#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    QWERTY,
    SYMB,
    NAV,
    ADJUST,
};

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

    [QWERTY] = LAYOUT_split_3x6_3(
        //,-----------------------------------------------------.                    ,-----------------------------------------------------.
       KC_TAB, KC_Q, KC_W, KC_F, KC_P, KC_B,                                 KC_J, KC_L, KC_U, KC_Y, KC_SCLN,  MT(MOD_LGUI, KC_DEL),
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        KC_ESC, KC_A, KC_R, KC_S, KC_T, KC_G,                                           KC_M, KC_N, KC_E, KC_I, KC_O, KC_UNDS,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        KC_LSFT, KC_Z, KC_X, KC_C, KC_D, KC_V,                                          KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, TT(NAV),
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                        KC_SPC, KC_LALT, KC_LCTL,                     KC_BSPC, TT(SYMB), KC_ENT
        //`--------------------------'  `--------------------------'

        ),

    [SYMB] = LAYOUT_split_3x6_3(
        //,-----------------------------------------------------.                    ,-----------------------------------------------------.
        TO(ADJUST), KC_EXLM, KC_AT, KC_NUHS, KC_AMPR, KC_LCBR,                            KC_RCBR, KC_PMNS, KC_PLUS, KC_EQL, KC_NO, KC_NO,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        TO(QWERTY), KC_PERC, KC_DLR, KC_HASH, KC_ASTR, KC_LPRN,                        KC_RPRN, KC_LEFT, KC_DOWN, KC_UP, KC_RIGHT, KC_HYPR,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        KC_LSFT, KC_INT4, KC_CIRC, KC_GRV, KC_INT3, KC_LBRC,                              KC_RBRC, KC_QUOT, KC_DQUO, KC_TILD, KC_NUBS, KC_MEH,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                            KC_TRNS, KC_TRNS, KC_TRNS,                KC_TRNS, KC_TRNS, KC_TRNS
        //`--------------------------'  `--------------------------'
        ),

    [NAV] = LAYOUT_split_3x6_3(
        //,-----------------------------------------------------.                    ,-----------------------------------------------------.
        KC_F12, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5,                                      KC_PAST, KC_PLUS, KC_7, KC_8, KC_9, KC_CALC,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        TO(QWERTY), KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,                                KC_PSLS, KC_PMNS, KC_4, KC_5, KC_6, KC_DOT,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        KC_TRNS, KC_APP, KC_F11, KC_F12, KC_F13, KC_F14,                              KC_PERC, KC_0, KC_1, KC_2, KC_3, KC_PDOT,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                            KC_TRNS, KC_TRNS, KC_TRNS,              KC_TRNS, KC_TRNS, KC_TRNS
        //`--------------------------'  `--------------------------'
        ),

    [ADJUST] = LAYOUT_split_3x6_3(
        //,-----------------------------------------------------.                    ,-----------------------------------------------------.
        XXXXXXX, KC_WSCH, XXXXXXX, KC_SLEP, KC_WAKE, KC_PWR,                           KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        TO(QWERTY), KC_MPRV, KC_MNXT, KC_MPLY, KC_MSTP, KC_MSEL,                      KC_TRNS, KC_TRNS, KC_TRNS, XXXXXXX, XXXXXXX, XXXXXXX,
        //|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLU, KC_VOLD,                         KC_TRNS, KC_TRNS, XXXXXXX, XXXXXXX, XXXXXXX, QK_BOOT,
        //|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
                                            KC_TRNS,KC_TRNS, KC_TRNS,                   KC_TRNS,KC_TRNS,KC_TRNS
        //`--------------------------'  `--------------------------'
        )};


const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][2] = {
    [QWERTY] = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU)},
    [SYMB]   = {ENCODER_CCW_CW(KC_VOLD, KC_VOLU)},
    [NAV]    = {ENCODER_CCW_CW(KC_MSTP, KC_MPLY)},
    [ADJUST] = {ENCODER_CCW_CW(KC_RIGHT, KC_LEFT)},
};


